apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  labels:
    app: finthenticate
spec:
  selector:
    app: finthenticate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
