apiVersion: apps/v1
kind: Deployment
metadata:
  name: finthenticate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finthenticate
  template:
    metadata:
      labels:
        app: finthenticate
    spec:
      containers:
        - name: finthenticate
          image: samirsauma121/finthenticate:latest
          imagePullPolicy: Always
        
          env:
          - name: NODE_ENV
            value: production
          - name: REACT_APP_API_URL
            value: "http://nginx-load-balancer.default.svc.cluster.local"
          - name: REACT_APP_WEBSOCKET_URL
            value: "ws://nginx-load-balancer.default.svc.cluster.local/ws"

          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: finthenticate
spec:
  selector:
    app: finthenticate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# Update the Nginx ConfigMap to include routing for the frontend
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        upstream websocket_servers {
            server websocket-server.default.svc.cluster.local:8080;
        }

        upstream frontend_servers {
            server finthenticate-frontend.default.svc.cluster.local:80;
        }

        server {
            listen 80;

            location /ws {
                proxy_pass http://websocket_servers;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
            }

            location / {
                proxy_pass http://frontend_servers;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }